server:
  type: default
  minThreads: 32
  applicationContextPath: /aco
  adminContextPath: /admin
  registerDefaultExceptionMappers: false
  applicationConnectors:
    - type: http
      port: 1234
      acceptorThreads: 1
  adminConnectors:
    - type: http
      port: 12345
  requestLog:
    appenders:
      - type: file
        currentLogFilename: /var/log/flipkart/apache-camel-poc/access.log
        archivedLogFilenamePattern: /var/log/flipkart/apache-camel-poc/access-%i.log
        logFormat: '%h [%date] %i{x-client-trace-id} "%r" %s %b %D'
        archive: true
        archivedFileCount: 3
        timeZone: IST
        maxFileSize: 500MB

environment: "local"
service: "apache-camel-poc"

swagger:
  resourcePackage: "com.flipkart.apache.camel"

